Fairing-15th/FairPlay_FE

- src/App.tsx
- src/components/TopNav.tsx
- src/pages/auth/FindPassword.tsx
- src/pages/auth/LoginPage.tsx
- src/pages/auth/SignUpPage.tsx
- src/pages/mypage/AttendeeSideNav.tsx
- src/pages/mypage/Info.tsx
- src/pages/mypage/Withdrawal.tsx
- 사용자 정보 조회 및 관리 페이지 추가
- 민감한 정보 자동 블러 처리 (이메일, 비밀번호, 전화번호)
- 인페이지 비밀번호 변경 폼 구현
- 회원탈퇴 확인 페이지 및 체크박스 추가
- 마이페이지 사이드바 네비게이션 컴포넌트 생성
- 상단바 사용자 아이콘을 마이페이지로 연결
- 페이지 디렉토리 구조 정리 (auth/, mypage/)
> feat: 마이페이지 기능 구현

- index.html
- src/App.tsx
- src/components/TopNav.tsx
- src/pages/CancelPolicy.tsx
- src/pages/EventDetail.tsx
- src/pages/EventOverview.tsx
- src/pages/Expectations.tsx
- src/pages/ExternalLink.tsx
- src/pages/MainPage.tsx
- src/pages/Reviews.tsx
- src/pages/VenueInfo.tsx
- src/pages/auth/FindPassword.tsx
- 행사 상세보기 장소정보 예매/취소안내 관람평 기대평 구현
- 외부예매처 링크 구현
- TobNav 로고 클릭 시 홈 화면 이동
- 비밀번호 찾기 임시 비밀번호 발송 클릭시 모달창 구현
- 행사목록 리스트형/캘린더형 구현
- 행사목록 카테고리 필터링 수정
- 행사목록 월 범위 필터 수정
- 홈화면 히어로섹션 애니메이션 추가 및 UI 수정
- 로그인 시 상단바 로그아웃으로 변경 (노트북으로 백엔드 연결 못해서 아직 테스트는 못했습니다)
> feat: EventDetailPage 탭 추가

- src/components/TopNav.tsx
> fix: 로그인 후 상단바 로그아웃 버튼 표시 문제 해결

- src/pages/mypage/MyReview.tsx
> feat: write-review

- src/components/TopNav.tsx
- 알림 모달 UI 구현
- 로그인/로그아웃 상태에 따른 알림 접근 제어
- 새 알림과 지난 알림 섹션 분리
- 알림 클릭 시 읽음 상태 변경
- 로그인 상태에서만 붉은 점 표시
> feat: 알림 시스템 구현

- src/pages/mypage/MyReview.tsx
- 관람평 작성 상태 표시 (작성 전/완료 배지)
- 비공개 설정 기능 추가
- 일괄 삭제 기능 구현
- 삭제 확인 모달 추가
- 공개/비공개 상태 표시
- 수정 기능 구현
- 행사 리스트 다양화
- UI/UX 개선 (버튼 스타일, 모달 위치 등)
> feat: 관람평 관리 기능 추가

- src/App.tsx
- src/components/TopNav.tsx
- src/pages/MainPage.tsx
- src/pages/RegisterEvent.tsx
- 상단바 REGISTER -> 행사 등록 신청 페이지
- 상단바 위 여백 제거
> feat: 행사등록신청페이지 및 상단바 여백 조절

- src/App.tsx
- src/components/HostSideNav.tsx
- src/components/TopNav.tsx
- src/pages/HostDashboard.tsx
- src/pages/user_auth/LoginPage.tsx
- src/services/api.ts
행사 관리자 페이지 대시 보드 구현
- 행사 관리자 계정 로그인 시 대시보드 화면
- 행사 관리자 계정 마이페이지 -> 대시보드 화면
- 임의로 takonism@naver.com 계정 행사관리자로 지정해놨어요!
> feat: host-dashboard

- src/pages/MainPage.tsx
- src/pages/user_event/EventDetail.tsx
- 메인페이지 행사 목록에서 좋아요 버튼 누르면 상세페이지로 가는 오류 수정
- 상세페이지에 좋아요 버튼 추가
> 메인페이지 좋아요 버튼 오류 수정 및 행사상세 좋아요 버튼 추가

- src/App.tsx
- src/components/HostSideNav.tsx
- src/pages/host_event/EditEventInfo.tsx
- src/pages/host_event/EventVersionComparison.tsx
- src/pages/host_event/EventVersionDetail.tsx
- src/pages/host_event/EventVersionManagement.tsx
- 행사 버전 관리 페이지 추가
- 행사 버전 상세보기 추가
- 행사 버전 비교 임시 구현
- 행사 상세 정보 페이지 수정
> feat: 행사 버전 관리, 상세보기, 비교

- src/components/ticket/TicketFormModal.tsx
- src/pages/host_event/TicketManagement.tsx
- src/services/ticketService.ts
- TicketFormModal 수정 모드에서 기존 데이터가 올바르게 표시되도록 초기화 로직 개선
- 수정 모드에서 새 데이터 추가 대신 기존 데이터 업데이트되도록 ID 매핑 수정
- TicketManagement에서 하드코딩된 select 옵션을 AudienceType 상수로 동적 생성
- Ticket 인터페이스와 ticketService를 실제 API 응답 구조에 맞게 업데이트
> feat: 티켓 관리 화면 구현 (등록, 조회, 수정, 삭제)

- src/components/QrTicket.tsx
- src/pages/QRScanPage.tsx
- 입퇴장 토글버튼 생성
- 예시
- 입퇴장 QR 또는 수동코드 요청 API 연결 완료
- 역할 보안 추가 예정
- 행사 정보는 예약 API 연결된 후 예약 정보로 바꿀 예정
> feat: 입장, 퇴장 QR 또는 수동코드 요청 API 연결

- src/App.tsx
- src/pages/admin_statistics/PopularEvents.tsx
- src/pages/admin_statistics/ReservationStatistics.tsx
> feat: admin statistics

- src/pages/user_event/EventDetail.tsx
- src/pages/user_event/EventOverview.tsx
- 비로그인 상태에서 관심 버튼 클릭 시 로그인 페이지로 이동
- 로그인 후 원래 페이지로 돌아올 수 있도록 location.state에 경로 저장
> feat: 로그인 권한 체크 로직 추가

- src/components/AdminSideNav.tsx
- src/pages/admin_settlement/RemittanceHistory.tsx
- src/pages/admin_settlement/SettlementManagement.tsx
- src/pages/user_event/EventDetail.tsx
- 행사 상세 페이지 더미 데이터 삭제
- 매출 통계, 송금 정산 수정
> fix: admin-settlement, event-detail

- src/App.tsx
- src/components/HostSideNav.tsx
- src/pages/host_reservation/ReservationList.tsx
- src/services/reservationService.ts
- src/services/types/reservationType.ts
- 서버 사이드 페이지네이션
- 백엔드 API와 연동한 검색 필터링 구현
- 엑셀 다운로드 서버 사이드 처리로 변경
- 검색 조건 초기화 기능 추가
- URL 파라미터 기반 eventId 유효성 검사 강화
- 테이블 UI 개선: 가운데 정렬, 반응형 컬럼 너비
- 회차 정보 컬럼 추가 및 텍스트 오버플로우 처리
- 버튼 스타일 통일 (5px border-radius)
>   feat: (행사담당자) 예약자 목록 백엔드 API 연결 및 페이지네이션 구현

- src/pages/user_event/EventDetail.tsx
- src/services/paymentService.ts
- 무료 티켓 결제 에러관련 수정
- 오늘 이전 날짜에 대해 달력에서 회차 선택할 수 없도록 수정
> fix: 무료(0원) 결제 오류 및 회차 오류 관련 수정

- public/images/bell-outline.svg
- src/App.css
- src/components/Footer.tsx
- src/components/TopNav.tsx
- src/components/chat/ChatFloatingButton.tsx
- src/pages/MainPage.tsx
- src/pages/host_event/AdvertisementApplication.tsx
- 모바일 반응형 메인화면 적용
- 모바일 반응형 상단바, 하단네비게이션
> 모바일 반응형 메인화면 적용

- src/components/TopNav.tsx
- src/components/chat/ChatModal.tsx
- src/pages/MainPage.tsx
- src/pages/user_auth/FindPassword.tsx
- 비밀번호 찾기 페이지 모바일 적용
- 상단바 새알림 표시(빨간 점) 크기와 위치 수정해서 잘리지 않게 수정
- 알림패널 애니메이션 추가
- 채팅창 애네메이션 추가
> Fix/auth mobile UI

- src/App.tsx
- src/components/BoothAdminSideNav.tsx
- src/components/HostSideNav.tsx
- src/components/TopNav.tsx
- src/components/booth/BoothExperienceFormModal.tsx
- src/pages/booth_admin/BoothAdminDashboard.tsx
- src/pages/booth_admin/BoothExperienceManagement.tsx
- src/pages/booth_admin/BoothExperienceReserverManagement.tsx
- src/pages/booth_admin/BoothQRScanPage.tsx
- src/pages/booth_admin/ExperienceDetailPage.tsx
- src/pages/user_auth/KakaoCallback.tsx
- src/pages/user_auth/LoginPage.tsx
부스관리자 페이지
- 부스 현황
- 체험 관리
- 예약 현황
> feat: booth-admin-page

- src/components/TopNav.tsx
- src/pages/user_event/EventDetail.tsx
- src/pages/user_event/TicketReservation.tsx
- src/pages/user_mypage/Info.tsx
- src/pages/user_mypage/MyTickets.tsx
- src/pages/user_mypage/Reservation.tsx
- src/pages/user_refund/RefundList.tsx
- src/pages/user_refund/RefundRequestModal.tsx
1. 모바일 화면 적용
- 예약/결제
- 내 정보 조회
- 내 티켓
2. UI 수정
- 모바일 하단 네비게이션 이름 수정
- EventDetail 행사 소개 -> 소개로 간략화(줄바꿈 방지)
- 취소/환불 페이지 및 환불 모달
> Feat/mypage mobile UI

- src/pages/RegisterEvent.tsx
- src/pages/user_event/EventOverview.tsx
- src/pages/user_mypage/MyTickets.tsx
- 모바일 팜플렛
- 이벤트오버뷰 지도형 카드 깜빡임 수정
- 행사등록신청 페이지 모바일 적용
> Feat/apply mobile UI

- src/index.css
- src/pages/user_event/EventDetail.tsx
이벤트 디테일 페이지
- 페이지 접속 시 맨 위로 스크롤
- 카테고리 위치 수정
- 날짜선택 회차선택 시 전체 행사일 현황에 해당 회차로 자동 스크롤 적용
- 모바일 환경 가격 정보 레이아웃 수정
> fix: UI bug bash 2

- src/index.css
- src/pages/EventRegistrationIntro.tsx
> feat: 행사 등록 인트로 페이지 UI 수정

- src/pages/host_analytics/TimeAnalysis.tsx
- src/services/hourlyStatisticsService.ts
- src/services/types/hourlyStatsType.ts
> Feat: 시간대별 통계 
